<%@ Page Title="" Language="C#" MasterPageFile="~/View/Admin/AdminMasterPage.Master" AutoEventWireup="true" CodeBehind="VHouse.aspx.cs" Inherits="SocietyManagementSystem.View.Admin.VHouse" %>
<asp:Content ID="Content1" ContentPlaceHolderID="head" runat="server">
</asp:Content>
<asp:Content ID="Content2" ContentPlaceHolderID="ContentPlaceHolder1" runat="server">
     <div class="container-fluid">
        <div class="row">
        <div class="row">
            <div style="text-align:center;background:#ff6a00;color:white;font-weight:bolder;height:50px;padding-top:10px;font-size:20px">
                <asp:Label Text="HOUSE REPORT" runat="server"/>
            </div>
        </div>
        <div class="row" style="margin-top:30px">
            <div class="col-md-4">
                <div class="row">
                <div class="form-group">
                        <label for="selectsociety">Select Society:</label>
                      <div class="mt-3" style="display:inline">
                    <asp:DropDownList ID="selectSociety" runat="server"></asp:DropDownList>
                          </div>
                        <asp:Button Text=" View " class="btn mt-3 btn-success" runat="server" ID="ViewButton"  style="margin-left:10px" OnClick="ViewButton_Click"/>
                          
                    <div class="col-md-2">
                    </div>
                    </div>
                    </div>
              </div>
        </div>
            <div>
                <label runat="server" id="ErrMsg" class="text-danger"></label>

            </div>
            <asp:Label Text="" ID="status" runat="server" />
            <br/><br/>
           <div class="row" style="padding-left:20px; padding-right:20px">
                    <asp:GridView ID="HouseViewGV" runat="server" class="table" AutoGenerateDeleteButton="true" CellPadding="4" ForeColor="#333333" GridLines="None" OnSelectedIndexChanged="HouseGV_SelectedIndexChanged">
                        <AlternatingRowStyle BackColor="White" />
                        <FooterStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <HeaderStyle BackColor="#990000" Font-Bold="True" ForeColor="White" />
                        <PagerStyle BackColor="#FFCC66" ForeColor="#333333" HorizontalAlign="Center" />
                        <RowStyle BackColor="#FFFBD6" ForeColor="#333333" />
                        <SelectedRowStyle BackColor="#FFCC66" Font-Bold="True" ForeColor="Navy" />
                        <SortedAscendingCellStyle BackColor="#FDF5AC" />
                        <SortedAscendingHeaderStyle BackColor="#4D0000" />
                        <SortedDescendingCellStyle BackColor="#FCF6C0" />
                        <SortedDescendingHeaderStyle BackColor="#820000" />

                    </asp:GridView>
                </div>
    </div>
        
     </div>
</asp:Content>
